### ISSUE TITLE
Failed to activate the ide-python package (languageclient vscode-jsonrpc\lib\main.js main entry)

### ISSUE THREAD

**Issue by Marvin-desmond** [atom-community/ide-python#241]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.7.1

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module 'C:\Users\user\.atom\packages\ide-python\node_modules\atom-languageclient\node_modules\vscode-jsonrpc\lib\main.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module 'C:\Users\user\.atom\packages\ide-python\node_modules\atom-languageclient\node_modules\vscode-jsonrpc\lib\main.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Module._resolveFilename (C:/Users/user/AppData/Local/atom/app-1.53.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (C:/Users/user/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (C:/Users/user/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:14:13)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:699:3)
    at Module.get_Module._compile (C:/Users/user/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (C:/Users/user/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (C:/Users/user/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:18:31)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:31:3)
    at Module.get_Module._compile (C:/Users/user/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (C:/Users/user/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (C:/Users/user/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/dist/main.js:13:5)
    at /packages/ide-python/dist/main.js:125:3)
    at Module.get_Module._compile (C:/Users/user/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (C:/Users/user/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (C:/Users/user/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:1:736531)
    at Package.requireMainModule (C:/Users/user/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3711337)
    at Package.activateNow (C:/Users/user/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3699321)
    at C:/Users/user/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (C:/Users/user/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1190051)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-live-server 2.3.0 
atom-wrap-in-tag 0.6.0 
busy-signal 2.0.1 
color-picker 2.3.0 
emmet 2.4.3 
Hydrogen 2.14.6 
ide-python 1.7.1 
intentions 1.1.5 
language-vue 0.26.0 
linter 3.1.1 
linter-ui-default 2.2.1 
platformio-ide-terminal 2.10.1 
prettier-atom 0.60.1 
tailwind-docs 1.0.0 
```

**Comment by clberube** [comment]
I had this error trace today after upgrading to ide-python 1.7.2 from the Atom GUI. 
The issue was resolved by running `apm install atom-ide-base` followed by `apm install ide-python` as suggested on the readme page. Maybe that helps someone.
Cheers.

**Comment by IfTrueReturnTrue** [comment]
This happened with me too

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
