### ISSUE TITLE
Failed to activate the ide-python package (version `GLIBCXX_3.4.22' not found)

### ISSUE THREAD

**Issue by kosmah** [atom-community/ide-python#255]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.04.1
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.7.1

### Stack Trace

Failed to activate the ide-python package

```
At /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc  .so.6: version `GLIBCXX_3.4.22' not found (required by /home/kosma/.atom/packages/ide-python/node_modules/fuzzaldrin-plus-fast/build/Release/fuzzaldrinplusfast.node)

Error: /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc  .so.6: version `GLIBCXX_3.4.22' not found (required by /home/kosma/.atom/packages/ide-python/node_modules/fuzzaldrin-plus-fast/build/Release/fuzzaldrinplusfast.node)
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/node_modules/fuzzaldrin-plus-fast/fuzzaldrin-dist.js:1:1650)
    at /packages/ide-python/node_modules/fuzzaldrin-plus-fast/fuzzaldrin-dist.js:1:3551)
    at /packages/ide-python/node_modules/fuzzaldrin-plus-fast/fuzzaldrin-dist.js:4:3)
    at Module.get_Module._compile (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/adapters/autocomplete-adapter.js:14:32)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/adapters/autocomplete-adapter.js:394:3)
    at Module.get_Module._compile (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:18:32)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:699:3)
    at Module.get_Module._compile (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:18:31)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:31:3)
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-file-icons 0.7.1 
atom-live-server 2.3.0 
busy-signal 2.0.1 
emmet 2.4.3 
highlight-selected 0.17.0 
Hydrogen 2.14.6 
ide-java 0.9.1 
ide-python 1.7.1 
intentions 1.1.5 
language-vue 0.26.0 
linter 3.1.1 
linter-jscs 4.2.4 
linter-jshint 3.1.19 
linter-ui-default 2.3.5 
minimap 4.36.7 
minimap-pigments 0.2.2 
pigments 0.40.6 
todo 0.6.0 
```

**Comment by aminya** [comment]
Did you install Atom using Snap?

**Comment by kosmah** [comment]
Hey! That's possible, I've been distro hopping like crazy for some days and I didn't know the horrors of snap store yet. Sorry for the mess, I was only half-aware I created this thread. Thank you so much for trying to help but I guess I'll just ditch Atom for a while and stick to learning Vim on my snap-free Pop! OS, cheers ;)

**Comment by aminya** [comment]
@kosmah Download the official binaries.
https://atom.io/

 Snap is not supported by Atom. Here is why:
https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md
