### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by reejusingh** [atom-community/ide-python#261]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.7.2

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module './cjs/react.production.min.js'
Require stack:
- C:\Users\G\.atom\packages\ide-python\node_modules\react\index.js
- C:\Users\G\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\G\.atom\packages\ide-python\dist\main.js
- C:\Users\G\AppData\Local\atom\app-1.53.0\resources\app.asar\static\index.html

Error: Cannot find module './cjs/react.production.min.js'
Require stack:
- C:\Users\G\.atom\packages\ide-python\node_modules\react\index.js
- C:\Users\G\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\G\.atom\packages\ide-python\dist\main.js
- C:\Users\G\AppData\Local\atom\app-1.53.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.53.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/node_modules/react/index.js:4:20)
    at /packages/ide-python/node_modules/react/index.js:9:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/dist/debugger/main.js:14:37)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:125:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:1:736531)
```

### Commands

```
```

### Non-Core Packages

```
ide-python 1.7.2 
script 3.29.3 
```

**Comment by aminya** [comment]
Please try to install the package again. This is just a connection issue.
