### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by 3xploiton3** [atom-community/ide-python#266]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Enterprise LTSC
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.7.2

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module 'fuzzaldrin-plus'
Require stack:
- C:\Users\Thinkpad-T430s\.atom\packages\ide-python\node_modules\atom-languageclient\build\lib\adapters\autocomplete-adapter.js
- C:\Users\Thinkpad-T430s\.atom\packages\ide-python\node_modules\atom-languageclient\build\lib\auto-languageclient.js
- C:\Users\Thinkpad-T430s\.atom\packages\ide-python\node_modules\atom-languageclient\build\lib\main.js
- C:\Users\Thinkpad-T430s\.atom\packages\ide-python\dist\main.js
- C:\Users\Thinkpad-T430s\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html

Error: Cannot find module 'fuzzaldrin-plus'
Require stack:
- C:\Users\Thinkpad-T430s\.atom\packages\ide-python\node_modules\atom-languageclient\build\lib\adapters\autocomplete-adapter.js
- C:\Users\Thinkpad-T430s\.atom\packages\ide-python\node_modules\atom-languageclient\build\lib\auto-languageclient.js
- C:\Users\Thinkpad-T430s\.atom\packages\ide-python\node_modules\atom-languageclient\build\lib\main.js
- C:\Users\Thinkpad-T430s\.atom\packages\ide-python\dist\main.js
- C:\Users\Thinkpad-T430s\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/adapters/autocomplete-adapter.js:13:27)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/adapters/autocomplete-adapter.js:339:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:16:32)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:677:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:10:31)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:23:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/dist/main.js:13:5)
```

### Commands

```
```

### Non-Core Packages

```
ide-python 1.7.2 
```

**Comment by aminya** [comment]
This is a connection issue. Please re-download
```
apm uninstall ide-python
apm install ide-python
```
