### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by Kuero2137** [atom-community/ide-python#268]
**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: "Arch Linux"
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.7.2

### Stack Trace

Failed to activate the ide-python package

```
At Package not initialized

Error: Package not initialized
    at /packages/atom-ide-ui/modules/nuclide-commons-atom/createPackage.js:61:15)
    at Provider.module.exports.Provider.provide (/usr/lib/atom/node_modules/service-hub/lib/provider.js:34:52)
    at ServiceHub.module.exports.ServiceHub.provide (/usr/lib/atom/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.activateServices (/usr/lib/atom/src/package.js:430:40)
    at Package.activateNow (/usr/lib/atom/src/package.js:246:14)
    at /usr/lib/atom/src/package.js:1058:18
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at /usr/lib/atom/src/package-manager.js:811:36
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:810:37)
    at /usr/lib/atom/node_modules/settings-view/lib/package-manager.js:477:29
    at exit (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:114:16)
    at triggerExitCallback (/usr/lib/atom/src/buffered-process.js:280:9)
    at /usr/lib/atom/src/buffered-process.js:301:9
    at Socket.<anonymous> (/usr/lib/atom/src/buffered-process.js:169:7)
    at Socket.emit (events.js:205:15)
    at Pipe.<anonymous> (net.js:586:12)
```

### Commands

```
     -1:17.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
     -0:26.8.0 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-base 2.1.1 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-python-run 0.9.7 
ide-python 1.7.2 
platformio-ide-terminal 2.10.1 
python-tools 0.6.9 
script 3.29.3 
teletype 0.13.4 
```

**Comment by aminya** [comment]
Please uninstall atom-ide-ui and use atom-ide-base
