### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by sreemanpisupat** [atom-community/ide-python#269]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.7
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.7.2

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module '/Users/venkatap/.atom/packages/ide-python/node_modules/temp/node_modules/rimraf/rimraf.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module '/Users/venkatap/.atom/packages/ide-python/node_modules/temp/node_modules/rimraf/rimraf.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Module._resolveFilename (/private/var/folders/rd/hx3dy7zn0s1dlr6x9h2czfh40000gp/T/AppTranslocation/B52505CC-3EAD-4641-BEF7-2036646C6FCB/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (/private/var/folders/rd/hx3dy7zn0s1dlr6x9h2czfh40000gp/T/AppTranslocation/B52505CC-3EAD-4641-BEF7-2036646C6FCB/d/Atom.app/Contents/Resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/private/var/folders/rd/hx3dy7zn0s1dlr6x9h2czfh40000gp/T/AppTranslocation/B52505CC-3EAD-4641-BEF7-2036646C6FCB/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/temp/lib/temp.js:5:18)
    at /packages/ide-python/node_modules/temp/lib/temp.js:316:3)
    at Module.get_Module._compile (/private/var/folders/rd/hx3dy7zn0s1dlr6x9h2czfh40000gp/T/AppTranslocation/B52505CC-3EAD-4641-BEF7-2036646C6FCB/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (/private/var/folders/rd/hx3dy7zn0s1dlr6x9h2czfh40000gp/T/AppTranslocation/B52505CC-3EAD-4641-BEF7-2036646C6FCB/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/rd/hx3dy7zn0s1dlr6x9h2czfh40000gp/T/AppTranslocation/B52505CC-3EAD-4641-BEF7-2036646C6FCB/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-commons/fsPromise.js:20:36)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-commons/fsPromise.js:763:3)
    at Module.get_Module._compile (/private/var/folders/rd/hx3dy7zn0s1dlr6x9h2czfh40000gp/T/AppTranslocation/B52505CC-3EAD-4641-BEF7-2036646C6FCB/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (/private/var/folders/rd/hx3dy7zn0s1dlr6x9h2czfh40000gp/T/AppTranslocation/B52505CC-3EAD-4641-BEF7-2036646C6FCB/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/rd/hx3dy7zn0s1dlr6x9h2czfh40000gp/T/AppTranslocation/B52505CC-3EAD-4641-BEF7-2036646C6FCB/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-adb/lib/AdbService.js:35:41)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-adb/lib/AdbService.js:200:3)
    at Module.get_Module._compile (/private/var/folders/rd/hx3dy7zn0s1dlr6x9h2czfh40000gp/T/AppTranslocation/B52505CC-3EAD-4641-BEF7-2036646C6FCB/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (/private/var/folders/rd/hx3dy7zn0s1dlr6x9h2czfh40000gp/T/AppTranslocation/B52505CC-3EAD-4641-BEF7-2036646C6FCB/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-python-run 0.9.7 
atom-runner 2.7.1 
ide-python 1.7.2 
script 3.29.3 
```

**Comment by aminya** [comment]
Please re-download. This is a connection issue

**Comment by sreemanpisupat** [comment]
ok
