### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by Ultima-Ignotum** [atom-community/ide-python#271]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.7.2

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module 'C:\Users\Admin\.atom\packages\ide-python\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\main.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module 'C:\Users\Admin\.atom\packages\ide-python\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\main.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/vscode-languageserver-protocol/lib/main.js:10:26)
    at /packages/ide-python/node_modules/vscode-languageserver-protocol/lib/main.js:44:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/languageclient.js:17:10)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/languageclient.js:400:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/convert.js:3:12)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/convert.js:204:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
```

### Commands

```
     -0:16.3.0 application:open-file (input.hidden-input)
```

### Non-Core Packages

```
ide-python 1.7.2 
script 3.29.3 
```

**Comment by aminya** [comment]
This is a connection issue. Please redownload
