### ISSUE TITLE
Failed to activate the ide-python package after updating last version

### ISSUE THREAD

**Issue by fsuarezj** [atom-community/ide-python#273]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.7.3

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module './cjs/react.production.min.js'
Require stack:
- C:\Users\FSuarezJimenez\.atom\packages\ide-python\node_modules\react\index.js
- C:\Users\FSuarezJimenez\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\FSuarezJimenez\.atom\packages\ide-python\dist\main.js
- C:\Users\FSuarezJimenez\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html

Error: Cannot find module './cjs/react.production.min.js'
Require stack:
- C:\Users\FSuarezJimenez\.atom\packages\ide-python\node_modules\react\index.js
- C:\Users\FSuarezJimenez\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\FSuarezJimenez\.atom\packages\ide-python\dist\main.js
- C:\Users\FSuarezJimenez\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/atom-ide-ui/node_modules/react/index.js:4:20)
    at /packages/atom-ide-ui/node_modules/react/index.js:9:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/dist/debugger/main.js:14:37)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:125:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:1:723602)
```

### Commands

```
```

### Non-Core Packages

```
atom-django 0.3.2 
atom-ide-ui 0.13.0 
atom-python-run 0.9.7 
atom-python-virtualenv 1.0.4 
autocomplete-python 1.17.0 
data-atom 0.29.1 
ex-mode 0.18.0 
Hydrogen 2.14.7 
ide-json 0.2.1 
ide-python 1.7.3 
kite 0.198.0 
python-indent 1.2.6 
python-tools 0.6.9 
vim-mode-plus 1.36.4 
vim-mode-plus-macros 0.1.2 
```

**Comment by aminya** [comment]
This is a connection issue. Please redownload:
```
apm install ide-python --verbose
```
