### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by sxd5** [atom-community/ide-python#279]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.7.3

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- C:\Users\Subhankar Behera\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\Subhankar Behera\.atom\packages\ide-python\dist\main.js
- C:\Users\Subhankar Behera\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html

Error: Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- C:\Users\Subhankar Behera\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\Subhankar Behera\.atom\packages\ide-python\dist\main.js
- C:\Users\Subhankar Behera\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/dist/debugger/main.js:12:51)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:125:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:1:723602)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3670531)
    at Package.activateNow (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3658515)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1191622)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:384090)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:382841
```

### Commands

```
```

### Non-Core Packages

```
atom-python-run 0.9.7 
atom-runner 2.7.1 
autocomplete-clang 0.13.1 
autocomplete-python 1.17.0 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.46 
ide-python 1.7.3 
intentions 1.1.5 
kite 0.202.0 
language-ini 1.23.0 
linter 3.3.0 
linter-gcc2 0.8.8 
linter-ui-default 3.2.2 
platformio-ide 2.7.2 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.1 
project-manager 3.3.8 
project-manager-ide 0.10.0 
python-debugger 0.2.0 
remote-ftp 2.2.4 
script 3.29.3 
tool-bar 1.4.2 
```

**Comment by aminya** [comment]
This is a connection issue. Please re-download:

```
apm install ide-python
```
