### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by Burseys** [atom-community/ide-python#287]
[Enter steps to reproduce:]

1. Load Atom
2. error appears

I did recently reinstall python as 64 bit, where it was 32 bit before, but have used atom a few times since then before this error occurred.

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.7.3

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module 'react'
Require stack:
- C:\Users\simon\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\simon\.atom\packages\ide-python\dist\main.js
- C:\Users\simon\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html

Error: Cannot find module 'react'
Require stack:
- C:\Users\simon\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\simon\.atom\packages\ide-python\dist\main.js
- C:\Users\simon\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/dist/debugger/main.js:14:37)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:125:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:1:723602)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3670531)
    at Package.activateNow (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3658515)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1191622)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:384090)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:382841
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-debugger-python 0.7.3 
atom-python-run 0.9.7 
busy-signal 2.0.1 
ide-python 1.7.3 
intentions 1.1.5 
linter 3.3.0 
linter-flake8 2.4.0 
linter-ui-default 1.8.1 
```

**Comment by aminya** [comment]
This is a connection issue. Please re-download:

```
apm uninstall ide-python
apm install ide-python
```
