### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by yoosuf** [atom-community/ide-python#289]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.2.2
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.7.3

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- /Users/yoosuf/.atom/packages/ide-python/dist/debugger/main.js
- /Users/yoosuf/.atom/packages/ide-python/dist/main.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html

Error: Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- /Users/yoosuf/.atom/packages/ide-python/dist/debugger/main.js
- /Users/yoosuf/.atom/packages/ide-python/dist/main.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/dist/debugger/main.js:12:51)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:125:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:696987)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3542705)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3530689)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1191622)
    at PackageManager.triggerActivationHook (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:384394)
    at AtomEnvironment.updateProcessEnvAndTriggerHooks (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:721968)
    at async Promise.all (index 2)
```

### Commands

```
```

### Non-Core Packages

```
ide-python 1.7.3 
```

**Comment by aminya** [comment]
This is a connection issue. Please redownload:

```
apm uninstall ide-python 
apm install ide-python
```
