### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by SavageFC** [atom-community/ide-python#300]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.2.3
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.8.0

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module '/Users/ohmpanchal/.atom/packages/ide-python/node_modules/atom-languageclient/node_modules/vscode-jsonrpc/lib/node/main.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module '/Users/ohmpanchal/.atom/packages/ide-python/node_modules/atom-languageclient/node_modules/vscode-jsonrpc/lib/node/main.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Module._resolveFilename (/Users/ohmpanchal/Desktop/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (/Users/ohmpanchal/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Users/ohmpanchal/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:14:13)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:830:3)
    at Module.get_Module._compile (/Users/ohmpanchal/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (/Users/ohmpanchal/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Users/ohmpanchal/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:18:31)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:35:3)
    at Module.get_Module._compile (/Users/ohmpanchal/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (/Users/ohmpanchal/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Users/ohmpanchal/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/dist/main.js:13:5)
    at /packages/ide-python/dist/main.js:125:3)
    at Module.get_Module._compile (/Users/ohmpanchal/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (/Users/ohmpanchal/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
```

### Commands

```
```

### Non-Core Packages

```
atom-python-run 0.9.7 
Hydrogen 2.14.7 
ide-python 1.8.0 
kite 0.204.0 
scroll-through-time 0.3.1 
teletype 0.13.4 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
