### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by laurenmichaeljones** [atom-community/ide-python#302]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.8.0

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- C:\Users\laure\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\laure\.atom\packages\ide-python\dist\main.js
- C:\ProgramData\lauren\atom\app-1.55.0\resources\app.asar\static\index.html

Error: Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- C:\Users\laure\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\laure\.atom\packages\ide-python\dist\main.js
- C:\ProgramData\lauren\atom\app-1.55.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (C:/ProgramData/lauren/atom/app-1.55.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/dist/debugger/main.js:12:51)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:125:3)
    at Module.get_Module._compile (C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:1:736637)
    at requireModule (C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:14:1122229)
    at Package.requireMainModule (C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:11:3509026)
    at Package.activateNow (C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:11:3497010)
    at C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:11:1191622)
    at PackageManager.triggerDeferredActivationHooks (C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:11:384090)
    at C:/ProgramData/lauren/atom/app-1.55.0/resources/app/static/<embedded>:11:382841
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-django 0.3.2 
atom-python-run 0.9.7 
atom-python-test 1.0.1 
build 0.70.0 
build-python 0.13.0 
busy-signal 2.0.1 
docblock-python 0.19.1 
Hydrogen undefined 
ide-python 1.8.0 
kite 0.204.0 
python-debugger 0.2.0 
python-docstring 0.0.3 
python-indent 1.2.6 
python-mrigor 2.1.3 
python-snippets 1.9.0 
python-stero 0.2.0 
python-tools 0.6.9 
ubik-gotham-syntax 1.2.0 
ubik-hackerman-syntax 1.10.0 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
