### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by asiloisad** [atom-community/ide-python#306]
[Enter steps to reproduce:]

1. just type text in text editor

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.8.0

### Stack Trace

Uncaught Error: Connection is closed.

```
At C:\Users\asiloisad\.atom\packages\ide-python\node_modules\atom-languageclient\node_modules\vscode-jsonrpc\lib\common\connection.js:723

Error: Connection is closed.
    at throwIfClosedOrDisposed (/packages/ide-python/node_modules/atom-languageclient/node_modules/vscode-jsonrpc/lib/common/connection.js:723:19)
    at Object.sendNotification (/packages/ide-python/node_modules/atom-languageclient/node_modules/vscode-jsonrpc/lib/common/connection.js:805:13)
    at LanguageClientConnection._sendNotification (/packages/ide-python/node_modules/atom-languageclient/build/lib/languageclient.js:472:19)
    at LanguageClientConnection.didChangeWatchedFiles (/packages/ide-python/node_modules/atom-languageclient/build/lib/languageclient.js:251:14)
    at ServerManager.projectFilesChanged (/packages/ide-python/node_modules/atom-languageclient/build/lib/server-manager.js:252:41)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1191622)
    at s (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:411609)
    at PathWatcher.onNativeEvents (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:26758)
    at ~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:25494
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1191622)
    at NSFWNativeWatcher.onEvents (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:22740)
    at watcher.c.debounceMS (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:24389)
```

### Commands

```
     -0:47.9.0 find-and-replace:show (input.hidden-input)
  3x -0:46.4.0 find-and-replace:find-next (input.hidden-input)
  4x -0:41.1.0 core:delete (input.hidden-input)
     -0:38.2.0 editor:consolidate-selections (input.hidden-input)
     -0:38.2.0 core:cancel (input.hidden-input)
     -0:37.9.0 editor:consolidate-selections (input.hidden-input)
     -0:37.9.0 core:cancel (input.hidden-input)
     -0:37.2.0 editor:consolidate-selections (input.hidden-input)
     -0:37.2.0 core:cancel (input.hidden-input)
  5x -0:36.4.0 find-and-replace:find-next (input.hidden-input)
     -0:28.2.0 find-and-replace:show (input.hidden-input)
     -0:27.6.0 find-and-replace:use-selection-as-replace-pattern (input.hidden-input)
     -0:26.3.0 editor:consolidate-selections (input.hidden-input)
     -0:26.3.0 core:cancel (input.hidden-input)
  2x -0:25 core:delete (input.hidden-input)
     -0:24.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-file-icons 0.7.1 
atom-ide-ui 0.13.0 
atom-overtype-mode 0.4.0 
bacadra-tools 0.1.6 
banager-tools 0.0.1 
bib-finder 0.2.12 
browser-plus 0.0.98 
browser-plus-open-new-window 0.0.1 
busy-signal 2.0.1 
color-picker 2.3.0 
dbclick-tree-view 1.6.3 
hard-wrap 1.7.1 
hey-pane 1.2.0 
highlight-selected 0.17.0 
Hydrogen 2.14.7 
hydrogen-example 1.0.0 
hydrogen-launcher 1.2.2 
hydrogen-run 0.1.10 
ide-python 1.8.0 
ide-typescript 0.9.1 
image-paste 0.2.1 
indent-guide-improved 1.4.13 
bacadra-language 0.1.3 
language-batch 0.4.0 
language-cython 0.3.0 
language-gmsh 0.1.0 
language-ipynb 1.3.0 
language-latex 1.2.0 
language-markdown 0.37.0 
language-opensees 0.2.4 
language-restructuredtext 1.1.2 
sofistik-language 0.1.20 
language-tcl 0.1.2 
language-vbscript 0.9.0 
latex 0.50.2 
markdown-cell-highlight 1.2.0 
multi-cursor-plus 1.2.0 
navigation-pane 0.0.4 
open-terminal-here 2.3.2 
open-unsupported-files 1.0.20 
pdf-view-plus 1.11.0 
platformio-ide-terminal 2.10.1 
python-debugger 0.2.0 
python-tools 0.6.9 
revert-buffer 0.6.0 
sequential-number 0.5.0 
simple-align 0.2.0 
slickedit-select 1.6.2 
sofistik-tools 0.1.12 
sort-selected-elements 0.1.0 
split-diff 1.6.1 
tablr 1.8.3 
tabularize 0.2.5 
todo-show 2.3.2 
tree-view-copy-relative-path 1.2.0 
tree-view-git-status 1.5.3 
word-map 0.6.7 
```

**Comment by aminya** [comment]
Install the latest version
