### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by ssj4gotent** [atom-community/ide-python#309]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.8.0

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- C:\Users\Ryan M\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\Ryan M\.atom\packages\ide-python\dist\main.js
- C:\Users\Ryan M\AppData\Local\atom\app-1.53.0\resources\app.asar\static\index.html

Error: Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- C:\Users\Ryan M\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\Ryan M\.atom\packages\ide-python\dist\main.js
- C:\Users\Ryan M\AppData\Local\atom\app-1.53.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.53.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/dist/debugger/main.js:12:51)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:125:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:1:736531)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3711337)
    at Package.activateNow (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3699321)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1190051)
    at Emitter.emit (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1191492)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:383812
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:383774)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:916621
    at r (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:911227)
    at s (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:1134640)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:1134846)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
  5x -1:15.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-css-comb 3.5.1 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
auto-indent 0.5.0 
busy-signal 2.0.1 
color-picker 2.3.0 
file-type-icons 1.3.4 
ide-python 1.8.0 
intentions 1.1.5 
linter 2.3.1 
linter-js-standard 7.0.0 
linter-ui-default 1.8.1 
my-theme-syntax 0.0.0 
python-debugger 0.2.0 
```

**Comment by aminya** [comment]
Please redownload. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python.
```

https://github.com/atom/apm/issues/919
