### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by subashdon** [atom-community/ide-python#310]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro Education
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.8.0

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module 'C:\Users\subash chandra bose\.atom\packages\ide-python\node_modules\idx\lib\idx.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module 'C:\Users\subash chandra bose\.atom\packages\ide-python\node_modules\idx\lib\idx.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:301:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:532:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:10:35)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:14:62)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/dist/debugger/main.js:16:36)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-live-server 2.3.0 
autocomplete-python 1.17.0 
autosave-onchange 1.5.1 
emmet 2.4.3 
ide-html 0.6.2 
ide-python 1.8.0 
pigments 0.40.6 
platformio-ide-terminal 2.10.1 
terminus undefined 
unleash-django 1.3.2 
```

**Comment by subashdon** [comment]
whenever I open atom this kind of error is pop on my screen

**Comment by aminya** [comment]
This is an apm issue 
https://github.com/atom/apm/issues/919

Please uninstall ide-python, clean your cache, and install it again.
