### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by superbroker28** [atom-community/ide-python#312]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.8.0

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- C:\Users\JohnYoonSoo\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\JohnYoonSoo\.atom\packages\ide-python\dist\main.js
- C:\Users\JohnYoonSoo\AppData\Local\atom\app-1.56.0\resources\app.asar\static\index.html

Error: Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- C:\Users\JohnYoonSoo\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\JohnYoonSoo\.atom\packages\ide-python\dist\main.js
- C:\Users\JohnYoonSoo\AppData\Local\atom\app-1.56.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/dist/debugger/main.js:12:51)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:125:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:1:802769)
    at requireModule (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:14:1126115)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:3496608)
    at Package.activateNow (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:3484592)
    at ~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1182710)
    at Emitter.emit (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1184151)
```

### Commands

```
```

### Non-Core Packages

```
atom-django 0.3.2 
atom-python-run 0.9.7 
autocomplete-python 1.17.0 
ide-python 1.8.0 
platformio-ide-terminal 2.10.1 
```

**Comment by aminya** [comment]
This is a downloading issue. Please re-download.

```
apm uninstall ide-python
apm install ide-python

```
