### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by thelonelymars** [atom-community/ide-python#313]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.8.0

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module 'C:\Users\admin\.atom\packages\ide-python\node_modules\atom-languageclient\node_modules\vscode-jsonrpc\lib\node\main.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module 'C:\Users\admin\.atom\packages\ide-python\node_modules\atom-languageclient\node_modules\vscode-jsonrpc\lib\node\main.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:301:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:532:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (<embedded>:11:149153)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:14:13)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:841:3)
    at Module.get_Module._compile (<embedded>:11:149837)
    at Object.value [as .js] (<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (<embedded>:11:149153)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:18:31)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:35:3)
    at Module.get_Module._compile (<embedded>:11:149837)
    at Object.value [as .js] (<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (<embedded>:11:149153)
    at /packages/ide-python/dist/main.js:13:5)
    at /packages/ide-python/dist/main.js:125:3)
    at Module.get_Module._compile (<embedded>:11:149837)
    at Object.value [as .js] (<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (<embedded>:1:802769)
    at requireModule (<embedded>:14:1126115)
    at Package.requireMainModule (<embedded>:11:3496608)
    at Package.activateNow (<embedded>:11:3484592)
    at <embedded>:14:2607
    at Function.simpleDispatch (<embedded>:11:1182710)
    at Emitter.emit (<embedded>:11:1184151)
    at PackageManager.triggerDeferredActivationHooks (<embedded>:11:385466)
    at <embedded>:11:384217

```

### Commands

```
```

### Non-Core Packages

```
atom-file-icons 0.7.1 
atom-ide-base 2.6.0 
atom-ide-datatip 0.24.1 
atom-ide-markdown-service 2.1.0 
atom-ide-signature-help 0.15.3 
atom-java-snippets 0.5.1 
atom-material-syntax 1.0.8 
atom-python-package 0.7.1 
atom-python-run 0.9.7 
atom-python-test 1.0.1 
autocomplete-java 1.2.7 
autocomplete-python-jedi 1.10.3-0 
build 0.70.0 
busy-signal 2.0.1 
highlight-selected 0.17.0 
Hydrogen undefined 
ide-java 0.9.1 
ide-python 1.8.0 
intentions 1.1.5 
java-importer 1.4.1 
kite 0.204.0 
language-pip 2.0.1 
linter 3.3.1 
linter-ui-default 3.3.1 
minimap 4.39.13 
minimap-git-diff 4.3.6 
minimap-highlight-selected 4.6.5 
run 0.0.1 
run-in-terminal 1.0.1 
run-python-simply 0.6.0 
script 3.31.1 
vk-terminal 3.0.1 
```

**Comment by aminya** [comment]
This is a downloading issue. Please re-download
```
apm uninstall ide-python
apm install ide-python
```

https://github.com/atom/apm/issues/919
