### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by karthik-atom-dev** [atom-community/ide-python#315]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 20.04.2
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.8.0

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module './cjs/react.production.min.js'
Require stack:
- /home/karthik/.atom/packages/ide-python/node_modules/react/index.js
- /home/karthik/.atom/packages/ide-python/dist/debugger/main.js
- /home/karthik/.atom/packages/ide-python/dist/main.js
- /snap/atom/279/usr/share/atom/resources/app.asar/static/index.html

Error: Cannot find module './cjs/react.production.min.js'
Require stack:
- /home/karthik/.atom/packages/ide-python/node_modules/react/index.js
- /home/karthik/.atom/packages/ide-python/dist/debugger/main.js
- /home/karthik/.atom/packages/ide-python/dist/main.js
- /snap/atom/279/usr/share/atom/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (/snap/atom/279/usr/share/atom/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/snap/atom/279/usr/share/atom/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/node_modules/react/index.js:4:20)
    at /packages/ide-python/node_modules/react/index.js:9:3)
    at Module.get_Module._compile (/snap/atom/279/usr/share/atom/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/snap/atom/279/usr/share/atom/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/snap/atom/279/usr/share/atom/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/dist/debugger/main.js:14:37)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (/snap/atom/279/usr/share/atom/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/snap/atom/279/usr/share/atom/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/snap/atom/279/usr/share/atom/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:125:3)
    at Module.get_Module._compile (/snap/atom/279/usr/share/atom/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/snap/atom/279/usr/share/atom/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
```

### Commands

```
     -0:07.0 application:reopen-project (div#add-projects-view.)
```

### Non-Core Packages

```
atom-clock 0.1.18 
Hydrogen 2.15.3 
ide-java 0.9.1 
ide-python 1.8.0 
platformio-ide-terminal 2.10.1 
terminal-plus 0.14.5 
```

**Comment by karthik-atom-dev** [comment]
sorry im new to github so yeah plz help me with this issue im on ubuntu 20.04 btw thanks for helping

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
