### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by Rafale25** [atom-community/ide-python#317]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 20.04.2
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.8.0

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module './cjs/react.production.min.js'
Require stack:
- /home/rafale25/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react/index.js
- /home/rafale25/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/Checkbox.js
- /home/rafale25/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js
- /home/rafale25/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js
- /home/rafale25/.atom/packages/ide-python/dist/debugger/main.js
- /home/rafale25/.atom/packages/ide-python/dist/main.js
- /usr/share/atom/resources/app.asar/static/index.html

Error: Cannot find module './cjs/react.production.min.js'
Require stack:
- /home/rafale25/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react/index.js
- /home/rafale25/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/Checkbox.js
- /home/rafale25/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js
- /home/rafale25/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js
- /home/rafale25/.atom/packages/ide-python/dist/debugger/main.js
- /home/rafale25/.atom/packages/ide-python/dist/main.js
- /usr/share/atom/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149153)
    at /packages/atom-ide-ui/node_modules/react/index.js:4:20)
    at /packages/atom-ide-ui/node_modules/react/index.js:9:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/Checkbox.js:8:37)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/Checkbox.js:126:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:14:17)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
epitech-header-2018 4.0.2 
fonts 3.13.0 
highlight-selected 0.17.0 
ide-python 1.8.0 
minimap 4.39.13 
monokai 0.27.0 
open-no-binaries 0.1.1 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
