### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by hagilaash** [atom-community/ide-python#321]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.8.0

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module './cjs/react.production.min.js'
Require stack:
- C:\Users\hagilaash\.atom\packages\ide-python\node_modules\@atom-ide-community\nuclide-debugger-common\node_modules\react\index.js
- C:\Users\hagilaash\.atom\packages\ide-python\node_modules\@atom-ide-community\nuclide-debugger-common\DebuggerLaunchAttachProvider.js
- C:\Users\hagilaash\.atom\packages\ide-python\node_modules\@atom-ide-community\nuclide-debugger-common\AutoGenLaunchAttachProvider.js
- C:\Users\hagilaash\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\hagilaash\.atom\packages\ide-python\dist\main.js
- C:\Users\hagilaash\AppData\Local\atom\app-1.56.0\resources\app.asar\static\index.html

Error: Cannot find module './cjs/react.production.min.js'
Require stack:
- C:\Users\hagilaash\.atom\packages\ide-python\node_modules\@atom-ide-community\nuclide-debugger-common\node_modules\react\index.js
- C:\Users\hagilaash\.atom\packages\ide-python\node_modules\@atom-ide-community\nuclide-debugger-common\DebuggerLaunchAttachProvider.js
- C:\Users\hagilaash\.atom\packages\ide-python\node_modules\@atom-ide-community\nuclide-debugger-common\AutoGenLaunchAttachProvider.js
- C:\Users\hagilaash\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\hagilaash\.atom\packages\ide-python\dist\main.js
- C:\Users\hagilaash\AppData\Local\atom\app-1.56.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/node_modules/react/index.js:4:20)
    at /packages/ide-python/node_modules/react/index.js:9:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/DebuggerLaunchAttachProvider.js:8:37)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/DebuggerLaunchAttachProvider.js:75:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:10:60)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-ide-vue 1.4.6 
atom-python-run 0.9.7 
ide-python 1.8.0 
script 3.26.0 
server-script 0.1.3 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
