### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by abhay1412** [atom-community/ide-python#322]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.8.0

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module 'C:\Users\Rohan\.atom\packages\ide-python\node_modules\vscode-uri\lib\index.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module 'C:\Users\Rohan\.atom\packages\ide-python\node_modules\vscode-uri\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.53.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-commons/nuclideUri.js:8:41)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-commons/nuclideUri.js:839:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:20:42)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:14:62)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
```

### Commands

```
```

### Non-Core Packages

```
atom-js-console 1.2.2 
atom-runner 2.7.1 
exec-in-cmd 3.5.0 
go-build 0.2.2 
Hydrogen 2.15.3 
ide-python 1.8.0 
lang-gdscript 6.2.0 
open_in_cmd 0.6.1 
script 3.32.0 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
