### ISSUE TITLE
Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?inva...

### ISSUE THREAD

**Issue by Taiiwo** [atom-community/ide-python#325]
[Enter steps to reproduce:]

1. start with a completely fresh atom install
2. install python laguage server
3. install packages listed below as instructed by the readme
4. Try and open the debugger terminal
5. get the **two** stacktraces below.

I read a bit online and think that maybe the react-dom packages are the wrong version somehow.

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.8.0

### Stack Trace

Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

```
At C:\Users\taiiwo\.atom\packages\ide-python\node_modules\react-dom\cjs\react-dom.production.min.js:280

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Vg (/packages/ide-python/node_modules/react-dom/cjs/react-dom.production.min.js:280:177)
    at /packages/ide-python/node_modules/react-dom/cjs/react-dom.production.min.js:149:163
    at fi (/packages/ide-python/node_modules/react-dom/cjs/react-dom.production.min.js:176:186)
    at ck (/packages/ide-python/node_modules/react-dom/cjs/react-dom.production.min.js:270:437)
    at bk (/packages/ide-python/node_modules/react-dom/cjs/react-dom.production.min.js:250:347)
    at ak (/packages/ide-python/node_modules/react-dom/cjs/react-dom.production.min.js:250:278)
    at Tj (/packages/ide-python/node_modules/react-dom/cjs/react-dom.production.min.js:250:138)
    at Lj (/packages/ide-python/node_modules/react-dom/cjs/react-dom.production.min.js:243:163)
    at Jg (/packages/ide-python/node_modules/react-dom/cjs/react-dom.production.min.js:237:175)
    at lk (/packages/ide-python/node_modules/react-dom/cjs/react-dom.production.min.js:285:27)
    at /packages/ide-python/node_modules/react-dom/cjs/react-dom.production.min.js:289:301
    at Xj (/packages/ide-python/node_modules/react-dom/cjs/react-dom.production.min.js:244:244)
    at tk (/packages/ide-python/node_modules/react-dom/cjs/react-dom.production.min.js:289:287)
    at Object.exports.render (/packages/ide-python/node_modules/react-dom/cjs/react-dom.production.min.js:296:69)
    at HTMLElement.connectedCallback (/packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/ReactMountRootElement.js:64:23)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:152:22)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1187631)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:458810)
    at Pane.activateItem (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:461058)
    at DebuggerLayoutManager._appendItemToDock (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:323:20)
    at DebuggerLayoutManager._addPaneContainerToWorkspace (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:648:10)
    at DebuggerLayoutManager.showDebuggerViews (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:593:44)
    at DebuggerLayoutManager._reshowDebuggerPanes (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:203:12)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:65:10)
    at Object.activate (/packages/atom-ide-debugger/dist/main.js:114:20)
    at Package.activateNow (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3509169)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1187631)
```

### Stack Trace

Uncaught TypeError: call.getFileName is not a function

```
At assert.js:270

TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:270:25)
    at innerOk (assert.js:361:17)
    at ok (assert.js:381:3)
    at DebuggerLayoutManager._overridePaneInitialHeight (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:113:25)
    at Object.onPaneResize (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:149:14)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:354:24
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1187631)
    at Pane.setFlexScale (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:456811)
    at Pane.split (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:468012)
    at Pane.splitDown (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:467717)
    at DebuggerLayoutManager._appendItemToDock (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:325:20)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:632:14
    at Array.forEach (<anonymous>)
    at DebuggerLayoutManager.showDebuggerViews (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:606:181)
    at /packages/atom-ide-debugger/dist/main.js:412:24)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:352215)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:350690)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:833360)
    at EventEmitter.t (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:841331)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
     -0:17.8.0 debugger:show (atom-pane.pane)
```

### Non-Core Packages

```
atom-ide-base 2.6.0 
atom-ide-console 0.0.2 
atom-ide-datatip 0.24.1 
atom-ide-debugger 0.0.3 
atom-ide-debugger-python 0.7.3 
atom-ide-definitions 0.4.1 
atom-ide-hyperclick 1.0.10 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 2.3.4 
atom-ide-signature-help 0.15.3 
busy-signal 2.0.1 
ide-python 1.8.0 
intentions 1.1.5 
linter 3.3.1 
linter-ui-default 3.3.1 
```

**Comment by Taiiwo** [comment]
Upon investigation, the issue is in `\packages\atom-ide-debugger\node_modules\@atom-ide-community\nuclide-commons-ui\ReactMountRootElement.js` on line 64. The `Profiler` variable is used to represent the element type, but is undefined as it's set to `const Profiler = React.unstable_Profiler;` on line 40.

**Comment by Taiiwo** [comment]
Changing ` "react": "16.9.0",` to ` "react": "16.9.0",` on line 104 of package.json, the running `npm install --force` fixes this issue. Probably not the correct way to fix this as npm complains of multiple dependency conflicts while running, but otherwise makes the debugger work as intended.

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919

**Comment by Taiiwo** [comment]
I tried that multiple times from both within atom and with apm. I also reinstalled atom twice and deleted all configs. There's some version mismatching going on somwhere down the line.

**Comment by Taiiwo** [comment]
I should also add that while the above fix gets me past the error in this issue, and allows me to sucessfully load the debugging panel, there are no python debuggers listed (Even though I have the packages installed), and when I press `launch debugger` and enter my python path, I get an error message from the same library; react-dom. I tried changing the react version around a bit for this error but nothing seems to work.
