### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by b1d3k** [atom-community/ide-python#329]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.8.0

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module 'object-assign'
Require stack:
- C:\Users\Bibek\.atom\packages\ide-python\node_modules\react\cjs\react.production.min.js
- C:\Users\Bibek\.atom\packages\ide-python\node_modules\react\index.js
- C:\Users\Bibek\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\Bibek\.atom\packages\ide-python\dist\main.js
- C:\Users\Bibek\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html

Error: Cannot find module 'object-assign'
Require stack:
- C:\Users\Bibek\.atom\packages\ide-python\node_modules\react\cjs\react.production.min.js
- C:\Users\Bibek\.atom\packages\ide-python\node_modules\react\index.js
- C:\Users\Bibek\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\Bibek\.atom\packages\ide-python\dist\main.js
- C:\Users\Bibek\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/node_modules/react/cjs/react.production.min.js:10:20)
    at /packages/ide-python/node_modules/react/cjs/react.production.min.js:26:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/node_modules/react/index.js:4:20)
    at /packages/ide-python/node_modules/react/index.js:9:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/dist/debugger/main.js:14:37)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:125:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
file-icons 2.1.47 
gpp-compiler 3.0.7 
ide-python 1.8.0 
intentions 1.1.5 
linter 3.3.1 
linter-python 3.1.2 
linter-ui-default 3.3.1 
minimap 4.35.8 
pigments 0.40.6 
script 3.32.2 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
