### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by balakumarkk** [atom-community/ide-python#330]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.8.0

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- C:\Users\Admin\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\Admin\.atom\packages\ide-python\dist\main.js
- C:\Users\Admin\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html

Error: Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- C:\Users\Admin\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\Admin\.atom\packages\ide-python\dist\main.js
- C:\Users\Admin\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/dist/debugger/main.js:12:51)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:125:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1191588)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3520819)
    at Package.activateNow (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3508803)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1187631)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:385941)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:384692
    at TextEditorRegistry.updateAndMonitorEditorSettings (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:515427)
```

### Commands

```
     -0:14.4.0 settings-view:open (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-beautify undefined 
atom-html-preview 0.2.6 
atom-python-run 0.9.7 
atom-ternjs 0.20.0 
autoclose 0.0.2 
autocomplete-python-jedi 1.10.3-0 
color-tabs 0.1.8 
css-color-name 0.4.0 
csslint 1.2.0 
emmet 2.4.3 
ide-c-cpp 0.1.0 
ide-python 1.8.0 
language-ejs 0.4.0 
linter 3.3.1 
linter-eslint undefined 
linter-ui-default 3.3.1 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919

**Comment by ThatXliner** [comment]
> Please re-download. This is an apm issue
> 
> ```
> apm uninstall ide-python
> ```
> 
> Clear your cache then
> 
> ```
> apm install ide-python
> ```
> 
> [atom/apm#919](https://github.com/atom/apm/issues/919)

Maybe you should pin an issue like this... or get a bot.

**Comment by aminya** [comment]
😄 Yeah. I am tired of copy-pasting this message every time.

**Comment by jobalas** [comment]
> 

this did not help me. I tried it many times.

**Comment by t3dium** [comment]
it also didn't help me, i re-installed via apm, cleared cache, rebooted, tried on a seperate machine as well, no luck

**Comment by EboniLM** [comment]
Can confirm, the aforementioned steps of uninstalling and reinstalling via apm did not work for me either.

**Comment by t3dium** [comment]
> Can confirm, the aforementioned steps of uninstalling and reinstalling via apm did not work for me either.

You should probably switch ide’s anyways, since atom got discontinued. I’d recommend jetbrains personally.
