### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by rugby8724** [atom-community/ide-python#346]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Mac OS X 10.15.7
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.3

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /Users/jeremiahwise/.atom/packages/ide-python/node_modules/atom-languageclient/node_modules/vscode-jsonrpc/lib/common/messageReader.js:138

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-python/node_modules/atom-languageclient/node_modules/vscode-jsonrpc/lib/common/messageReader.js:138:27)
    at /packages/ide-python/node_modules/atom-languageclient/node_modules/vscode-jsonrpc/lib/common/messageReader.js:122:18)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

### Commands

```
     -1:43.5.0 intentions:highlight (input.hidden-input)
     -1:43.3.0 core:save (input.hidden-input)
     -1:42.6.0 intentions:highlight (input.hidden-input)
     -1:42.6.0 core:save (input.hidden-input)
     -1:41.9.0 intentions:highlight (input.hidden-input)
     -1:41.8.0 core:save (input.hidden-input)
     -1:41.1.0 intentions:highlight (input.hidden-input)
     -1:41.1.0 core:save (input.hidden-input)
     -1:40.3.0 intentions:highlight (input.hidden-input)
     -1:40.1.0 core:save (input.hidden-input)
     -1:38.9.0 intentions:highlight (input.hidden-input)
     -1:38.8.0 core:save (input.hidden-input)
     -1:38.1.0 intentions:highlight (input.hidden-input)
     -1:38 core:save (input.hidden-input)
     -1:37.2.0 intentions:highlight (input.hidden-input)
     -1:37.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-css-comb 3.5.1 
atom-html-preview 0.2.6 
atom-ide-ui 0.13.0 
atom-path-intellisense 1.2.2 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
busy-signal 2.0.1 
color-picker 2.3.0 
csslint 1.2.0 
django-atom 0.2.4 
emmet 2.4.3 
file-icons 2.1.47 
hyperclick 0.0.0 
ide-json 0.2.1 
ide-python 1.9.3 
intentions 2.1.1 
javascript-snippets 1.2.1 
language-ejs 0.4.0 
linter 3.4.0 
linter-eslint 8.6.6 
linter-ui-default 3.3.1 
pigments 0.40.6 
react 0.18.0 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by aminya** [comment]
Could you give more information about the reproduction of the bug?
