### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by Mohamed176b** [atom-community/ide-python#353]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.3

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module './cjs/react.production.min.js'
Require stack:
- C:\Users\User\.atom\packages\ide-python\node_modules\react\index.js
- C:\Users\User\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\User\.atom\packages\ide-python\dist\main.js
- C:\Users\User\AppData\Local\atom\app-1.51.0\resources\app.asar\static\index.html

Error: Cannot find module './cjs/react.production.min.js'
Require stack:
- C:\Users\User\.atom\packages\ide-python\node_modules\react\index.js
- C:\Users\User\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\User\.atom\packages\ide-python\dist\main.js
- C:\Users\User\AppData\Local\atom\app-1.51.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.51.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/node_modules/react/index.js:4:20)
    at /packages/ide-python/node_modules/react/index.js:9:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/dist/debugger/main.js:14:37)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:149:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
ide-python 1.9.3 
script 3.32.2 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
