### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by linuxnico** [atom-community/ide-python#361]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.4

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module 'C:\Users\xxxxxxxxxx\.atom\packages\ide-python\node_modules\atom-languageclient\node_modules\vscode-jsonrpc\lib\node\main.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module 'C:\Users\xxxxxxxxxxx\.atom\packages\ide-python\node_modules\atom-languageclient\node_modules\vscode-jsonrpc\lib\node\main.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:301:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:532:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:14:13)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:896:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:18:31)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:35:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/dist/main.js:13:5)
    at /packages/ide-python/dist/main.js:161:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

### Commands

```
```

### Non-Core Packages

```
atom-python-debugger 0.3.4 
atom-python-run 0.9.7 
busy-signal 2.0.1 
highlight-selected 0.17.0 
ide-python 1.9.4 
intentions 2.1.1 
linter 3.4.0 
linter-python 3.1.2 
linter-ui-default 3.4.1 
minimap 4.40.0 
minimap-highlight-selected 4.6.5 
minimap-selection 4.5.4 
```

**Comment by linuxnico** [comment]
arrived just after update of ide-package

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
