### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by alyssummontanum** [atom-community/ide-python#370]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 21.04
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.4

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module '/home/bartosz/.atom/packages/ide-python/node_modules/atom-languageclient/node_modules/vscode-jsonrpc/lib/node/main.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module '/home/bartosz/.atom/packages/ide-python/node_modules/atom-languageclient/node_modules/vscode-jsonrpc/lib/node/main.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:301:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:532:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:14:13)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:931:3)
    at Module.get_Module._compile (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:18:31)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:35:3)
    at Module.get_Module._compile (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:149153)
    at /packages/ide-python/dist/main.js:13:5)
    at /packages/ide-python/dist/main.js:161:3)
    at Module.get_Module._compile (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.1.0 
atom-ide-signature-help 0.16.0 
autocomplete 0.47.0 
autocomplete-python 1.17.0 
busy-signal 2.0.1 
file-header 1.13.9 
hey-pane 1.2.0 
highlight-selected 0.17.0 
Hydrogen undefined 
hyperclick 0.1.5 
ide-python 1.9.4 
intentions 2.1.1 
jupyter-notebook 0.0.10 
linter 3.4.0 
linter-ui-default 3.4.1 
multi-cursor 3.0.0 
python-tools 0.6.9 
script 3.32.2 
script-runner 2.6.0 
zentabs 0.8.9 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
