### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by solitude75** [atom-community/ide-python#372]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.2.3
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.4

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module './cjs/react.production.min.js'
Require stack:
- /Users/molokwuonyebuchimarcel/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/node_modules/react/index.js
- /Users/molokwuonyebuchimarcel/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/DebuggerLaunchAttachProvider.js
- /Users/molokwuonyebuchimarcel/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js
- /Users/molokwuonyebuchimarcel/.atom/packages/ide-python/dist/debugger/main.js
- /Users/molokwuonyebuchimarcel/.atom/packages/ide-python/dist/main.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html

Error: Cannot find module './cjs/react.production.min.js'
Require stack:
- /Users/molokwuonyebuchimarcel/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/node_modules/react/index.js
- /Users/molokwuonyebuchimarcel/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/DebuggerLaunchAttachProvider.js
- /Users/molokwuonyebuchimarcel/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js
- /Users/molokwuonyebuchimarcel/.atom/packages/ide-python/dist/debugger/main.js
- /Users/molokwuonyebuchimarcel/.atom/packages/ide-python/dist/main.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/react/index.js:4:20)
    at /packages/ide-python/node_modules/react/index.js:9:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/DebuggerLaunchAttachProvider.js:8:37)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/DebuggerLaunchAttachProvider.js:75:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:10:60)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at /packages/ide-python/dist/debugger/main.js:16:36)
```

### Commands

```
```

### Non-Core Packages

```
atom-python-run 0.9.7 
ide-java 0.9.1 
ide-python 1.9.4 
ipython-exec 1.2.0 
ipython-run 0.3.1 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
