### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by ilasdavide2011** [atom-community/ide-python#377]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.4

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- C:\Users\Davide\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\Davide\.atom\packages\ide-python\dist\main.js
- C:\ProgramData\Davide\atom\app-1.58.0\resources\app.asar\static\index.html

Error: Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- C:\Users\Davide\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\Davide\.atom\packages\ide-python\dist\main.js
- C:\ProgramData\Davide\atom\app-1.58.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (C:/ProgramData/Davide/atom/app-1.58.0/resources/app/static/<embedded>:11:157920)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (C:/ProgramData/Davide/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/ide-python/dist/debugger/main.js:12:51)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (C:/ProgramData/Davide/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (C:/ProgramData/Davide/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (C:/ProgramData/Davide/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:161:3)
    at Module.get_Module._compile (C:/ProgramData/Davide/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (C:/ProgramData/Davide/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (C:/ProgramData/Davide/atom/app-1.58.0/resources/app/static/<embedded>:1:802772)
    at requireModule (C:/ProgramData/Davide/atom/app-1.58.0/resources/app/static/<embedded>:14:1195622)
    at Package.requireMainModule (C:/ProgramData/Davide/atom/app-1.58.0/resources/app/static/<embedded>:11:3520513)
    at Package.activateNow (C:/ProgramData/Davide/atom/app-1.58.0/resources/app/static/<embedded>:11:3508497)
    at C:/ProgramData/Davide/atom/app-1.58.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (C:/ProgramData/Davide/atom/app-1.58.0/resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (C:/ProgramData/Davide/atom/app-1.58.0/resources/app/static/<embedded>:11:1188366)
```

### Commands

```
```

### Non-Core Packages

```
ide-python 1.9.4 
kite 0.206.0 
TabNine 3.0.3 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
