### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by 24tarun** [atom-community/ide-python#382]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.4

### Stack Trace

Failed to activate the ide-python package

```
At No native build was found for platform=win32 arch=x64 runtime=electron abi=80 uv=1 libc=glibc node=12.14.1 electron=9.4.4
    loaded from: C:\Users\tarun\.atom\packages\ide-python\node_modules\zadeh


Error: No native build was found for platform=win32 arch=x64 runtime=electron abi=80 uv=1 libc=glibc node=12.14.1 electron=9.4.4
    loaded from: C:\Users\tarun\.atom\packages\ide-python\node_modules\zadeh

    at Function.load.path (/packages/atom-ide-outline/node_modules/node-gyp-build/index.js:59:9)
    at load (/packages/atom-ide-outline/node_modules/node-gyp-build/index.js:21:30)
    at /packages/atom-ide-outline/node_modules/zadeh/index.js:1:2743)
    at /packages/atom-ide-outline/node_modules/zadeh/index.js:4:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/adapters/autocomplete-adapter.js:15:17)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/adapters/autocomplete-adapter.js:441:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:19:32)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:952:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:18:31)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.1.0 
atom-ide-signature-help 0.16.0 
busy-signal 2.0.1 
ide-python 1.9.4 
intentions 2.1.1 
linter 3.4.0 
linter-ui-default 3.4.1 
script 3.32.2 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
