### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by PrinterOMG** [atom-community/ide-python#387]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.5

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- C:\Users\Print\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\Print\.atom\packages\ide-python\dist\main.js
- C:\Users\Print\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html

Error: Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- C:\Users\Print\.atom\packages\ide-python\dist\debugger\main.js
- C:\Users\Print\.atom\packages\ide-python\dist\main.js
- C:\Users\Print\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:157920)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/ide-python/dist/debugger/main.js:12:51)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:162:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1195622)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3520513)
    at Package.activateNow (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3508497)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1188366)
```

### Commands

```
```

### Non-Core Packages

```
atom-python-run 0.9.7 
autocomplete-clang 0.13.1 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.47 
ide-python 1.9.5 
intentions 2.1.1 
language-ini 1.25.0 
linter 3.4.0 
linter-gcc2 0.8.8 
linter-pycodestyle 2.1.3 
linter-ui-default 3.4.1 
python-indent 1.2.6 
python-snippets 1.9.0 
python-tools 0.6.9 
tool-bar 1.4.4 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
