### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by IfTrueReturnTrue** [atom-community/ide-python#390]
[Enter steps to reproduce:]

1. Install ide-python package from package installer in atom
2. restart atom
3. For me, that's where the error message popped up

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.6

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module 'C:\Users\Administrator\.atom\packages\ide-python\node_modules\atom-languageclient\node_modules\vscode-jsonrpc\lib\node\main.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module 'C:\Users\Administrator\.atom\packages\ide-python\node_modules\atom-languageclient\node_modules\vscode-jsonrpc\lib\node\main.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:301:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:532:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:157920)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:14:13)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:952:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:18:31)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/main.js:35:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/ide-python/dist/main.js:13:5)
    at /packages/ide-python/dist/main.js:172:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.1.0 
atom-ide-signature-help 0.16.0 
atom-python-run 0.9.7 
autocomplete-python 1.17.0 
busy-signal 2.0.1 
ide-python 1.9.6 
intentions 2.1.1 
kite 0.206.0 
linter 3.4.0 
linter-ui-default 3.4.1 
platformio-ide-terminal 2.10.1 
python-tools 0.6.9 
teletype 0.13.4 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919

**Comment by IfTrueReturnTrue** [comment]
Yes thanks that worked
