### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by Eduardoqwerty** [atom-community/ide-python#391]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: "Manjaro Linux"
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.6

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- /home/eduardo/.atom/packages/ide-python/dist/debugger/main.js
- /home/eduardo/.atom/packages/ide-python/dist/main.js
- /usr/lib/atom/src/module-utils.js
- /usr/lib/atom/src/package.js
- /usr/lib/atom/src/package-manager.js
- /usr/lib/atom/src/atom-environment.js
- /usr/lib/atom/src/initialize-application-window.js
- /usr/lib/atom/static/index.html

Error: Cannot find module '@atom-ide-community/nuclide-commons/UniversalDisposable'
Require stack:
- /home/eduardo/.atom/packages/ide-python/dist/debugger/main.js
- /home/eduardo/.atom/packages/ide-python/dist/main.js
- /usr/lib/atom/src/module-utils.js
- /usr/lib/atom/src/package.js
- /usr/lib/atom/src/package-manager.js
- /usr/lib/atom/src/atom-environment.js
- /usr/lib/atom/src/initialize-application-window.js
- /usr/lib/atom/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:317:28)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at /packages/ide-python/dist/debugger/main.js:12:51)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:172:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at requireModule (/usr/lib/atom/src/module-utils.js:3:17)
    at Package.requireMainModule (/usr/lib/atom/src/package.js:909:27)
    at Package.activateNow (/usr/lib/atom/src/package.js:232:34)
    at /usr/lib/atom/src/package.js:1060:18
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.1.0 
atom-ide-signature-help 0.16.0 
busy-signal 2.0.1 
ide-python 1.9.6 
intentions 2.1.1 
linter 3.4.0 
linter-ui-default 3.4.1 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

https://github.com/atom/apm/issues/919
