### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by morteza-tajerii** [atom-community/ide-python#445]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 20.04.3
**Thrown From**: 'ide-python' package vundefined

### Stack Trace

Uncaught TypeError: invalid options argument

```
At /home/morteza/.atom/packages/ide-python/node_modules/mkdirp/lib/opts-arg.js:13

TypeError: invalid options argument
    at optsArg (/packages/ide-python/node_modules/mkdirp/lib/opts-arg.js:13:11)
    at mkdirp (/packages/ide-python/node_modules/mkdirp/index.js:11:10)
    at Object.save (/packages/save-session/lib/files.coffee:34:5)
    at /packages/save-session/lib/files.coffee:67:24
```

### Commands

```
     -1:45.1.0 snippets:next-tab-stop (input.hidden-input)
     -1:45.1.0 snippets:expand (input.hidden-input)
     -1:45.1.0 editor:indent (input.hidden-input)
     -1:43.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-debugger-python 0.7.3 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
auto-update-plus 0.11.4 
busy-signal 2.0.1 
expose 0.15.0 
file-icons 2.1.47 
highlight-selected 0.17.0 
Hydrogen 2.16.3 
intentions 2.1.1 
linter 3.4.0 
linter-ui-default 3.4.1 
minimap 4.40.0 
minimap-highlight-selected 4.6.6 
platformio-ide-terminal 2.10.1 
python-debugger 0.2.0 
python-indent 1.2.6 
save-session 0.15.7 
TabNine 4.0.7 
```

**Comment by morteza-tajerii** [comment]
I don't know what can I do for fix this
