### ISSUE TITLE
ide-python is throwing errors in builds `1.61.0-nightly2` and `1.61.0-nightly3`

### ISSUE THREAD

**Issue by DrKJeff16** [atom-community/ide-python#483]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

The package is throwing errors and Atom asked at some point for rebuilding the package (or something like that).

### Steps to Reproduce

1. Update from build `1.61.0-nightly1` to greater versions.

**Expected behavior:**

No errors thrown, and normal functionality.

**Actual behavior:**

Errors are thrown by Atom.

### Versions

**Atom**: 1.61.0-nightly3 x64
**Electron**: 11.4.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.7

### Stack Trace

Failed to activate the ide-python package

```
At call.getFileName is not a function

TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:278:25)
    at innerOk (assert.js:372:17)
    at ok (assert.js:392:3)
    at /packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:45:21)
    at /packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:305:3)
    at Module.get_Module._compile (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:149229)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:16:17)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module.get_Module._compile (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:149229)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:14:62)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module.get_Module._compile (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:149229)
    at /packages/ide-python/dist/debugger/main.js:16:36)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:149229)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:174:3)
    at Module.get_Module._compile (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:72:18)
    at customRequire (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:1:789785)
    at requireModule (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:14:1205790)
    at Package.requireMainModule (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:3287273)
    at Package.activateNow (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:3275272)
    at ~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:1187641)
    at Emitter.emit (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:1189082)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:386501)
    at ~/AppData/Local/atom-nightly/app-1.61.0-nightly3/resources/app/static/<embedded>:11:385252
```

### Commands

```
```

### Non-Core Packages

```
ascii-tree 1.2.1 
atom-bash 1.1.1 
atom-clock 0.1.18 
atom-discord 2.0.2 
atom-html-preview 0.2.7 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-console 0.0.2 
atom-ide-datatip 0.25.0 
atom-ide-debugger 0.0.3 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
atom-json 0.6.0 
atom-latex 0.9.1 
atom-visual-studio-code-ui 2.1.0 
autoclose-html 0.23.0 
bracket-colorizer 1.4.0 
busy 0.7.0 
busy-signal 2.0.1 
click-a-path 0.3.0 
color-indent 1.1.0 
dbg 1.6.3 
dbg-gdb 1.7.8 
directory-color 0.3.0 
dracula-syntax 3.0.2 
emmet 2.4.3 
file-header 1.13.9 
file-icons 2.1.47 
filesize 4.0.5 
flex-tool-bar 2.2.7 
font-viewer 1.0.5 
gpp-compiler 3.0.7 
highlight-bad-chars 2.0.0 
highlight-selected 0.17.0 
html-to-css 0.2.2 
hyperclick 0.1.5 
ide-cpp 0.1.0 
ide-csharp 0.6.2 
ide-css 0.4.0 
ide-html 0.7.0 
ide-java 0.9.1 
ide-json 0.2.1 
ide-python 1.9.7 
ide-typescript 0.9.5 
ide-yaml 0.8.0 
indent-detective 0.4.0 
ink 0.12.6 
intentions 2.1.1 
json-colorer 1.0.0 
julia-client 0.12.6 
language-assembly 0.7.2 
language-awk 0.1.12 
language-batchfile 0.7.7 
language-ini 1.25.0 
language-julia 0.22.1 
language-latex 1.2.0 
language-powershell 5.0.0 
language-viml 1.2.3 
language-x86asm 0.9.0 
latex 0.50.2 
latex-completions 0.3.6 
latex-tree 0.5.0 
line-number-color 0.2.0 
linter 3.4.0 
linter-clang-tidy 0.2.0 
linter-gcc 0.9.0 
linter-julia 0.9.0 
linter-markdown 5.2.11 
linter-tidy 2.4.0 
linter-ui-default 3.4.1 
lorem 4.0.0 
markdown-to-html 0.5.0 
markdown-to-pdf 0.1.1 
minimap 4.40.0 
minimap-linter 2.2.2 
monokai 0.28.0 
open_in_cmd 0.6.1 
org-mode 0.3.16 
output-panel 0.3.4 
pdf-view 0.73.0 
pigments 0.40.6 
pp 0.0.1 
pp-markdown 0.0.2 
python-indent 1.2.6 
rel-path-finder 1.3.4 
save-workspace 0.5.0 
script 3.32.2 
seti-syntax 1.2.0 
spaceduck-syntax 0.1.0 
sync-settings 5.2.15 
teletype 0.13.4 
template-generator 0.16.0 
todo-show 2.3.2 
tool-bar 1.4.4 
tree-view-sort 0.12.1 
uber-juno 0.3.0 
vim-mode-plus 1.36.7 
```

### Additional Information

This is likely due to latest pre-release builds moving to newer/different frameworks, just to keep you posted.

**Comment by ray-rock** [comment]
I'm on Arch Linux, latest updates as time of posting. running Atom v1.61.0-beta0. I'm encountering the same issue across three installed packages: 

---

- https://github.com/atom-community/ide-python
 <details>
 <summary>stack trace:</summary>

 ```
ide-python
TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:278:25)
    at innerOk (assert.js:372:17)
    at ok (assert.js:392:3)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:45:21)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:305:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/ray/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:16:17)
    at Object.<anonymous> (/home/ray/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/ray/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:14:62)
    at Object.<anonymous> (/home/ray/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
```

</details>

---

- https://github.com/atom-community/atom-ide-javascript

<details>
<summary>stack trace</summary>

```
atom-ide-javascript
TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:278:25)
    at innerOk (assert.js:372:17)
    at ok (assert.js:392:3)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:45:21)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:305:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:16:17)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:14:62)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
```

</details>

---

- https://github.com/atom-community/atom-ide-debugger

<details>
<summary>stack trace</summary>

```
atom-ide-debugger
TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:278:25)
    at innerOk (assert.js:372:17)
    at ok (assert.js:392:3)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:45:21)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:305:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/dist/ui/DebuggerLaunchAttachUI.js:18:17)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/dist/ui/DebuggerLaunchAttachUI.js:262:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/dist/main.js:52:54)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/dist/main.js:930:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
```


</details>



# My Conclusion
I ran into a few walls attempting to debug this because i'm not exactly a pro. I think this problem is an issue with atom itself, and not the packages themselves.

**Comment by charludo** [comment]
Same issue (and same packages) here. Did you find a solution?

**Comment by ray-rock** [comment]
> Same issue (and same packages) here. Did you find a solution?

At the risk of sounding a bit cheeky: I switched back to a point release distro, and atom v1.60, until the maintainers for these packages look into this issue.

**Comment by pbsds** [comment]
Related: #521 #518 #516 #511

**Comment by aminya** [comment]
See https://github.com/atom-community/atom-ide-javascript/issues/45#issuecomment-1325744112
