### ISSUE TITLE
call.getFileName is not a function

### ISSUE THREAD

**Issue by 0000matteo0000** [atom-community/ide-python#496]
### Versions

**Atom**: 1.61.0-nightly14 x64
**Electron**: 11.4.12
**OS**: Debian GNU/Linux
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.7

### Stack Trace

Failed to activate the ide-python package

```
At call.getFileName is not a function

TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:278:25)
    at innerOk (assert.js:372:17)
    at ok (assert.js:392:3)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:45:21)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:305:3)
    at Module.get_Module._compile (/usr/share/atom-nightly/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/usr/share/atom-nightly/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom-nightly/resources/app/static/<embedded>:11:149229)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:16:17)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module.get_Module._compile (/usr/share/atom-nightly/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/usr/share/atom-nightly/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom-nightly/resources/app/static/<embedded>:11:149229)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:14:62)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module.get_Module._compile (/usr/share/atom-nightly/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/usr/share/atom-nightly/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom-nightly/resources/app/static/<embedded>:11:149229)
    at /packages/ide-python/dist/debugger/main.js:16:36)
    at /packages/ide-python/dist/debugger/main.js:161:3)
    at Module.get_Module._compile (/usr/share/atom-nightly/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/usr/share/atom-nightly/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-debugger 0.1.6 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
atom-jinja2 0.6.0 
atom-latex 0.9.1 
atom-linter-phpstan 2.2.0 
atom-terminal-powershell 1.1.0 
atom-typescript 14.4.0 
atom-updater-linux 1.3.0 
auto-encoding 0.7.2 
autocomplete-java 1.2.7 
autocomplete-lua 0.9.2 
busy-signal 2.0.1 
data-atom 0.29.1 
emmet 2.4.3 
file-icons 2.1.47 
find-scroll-marker 0.1.3 
flow-ide 1.13.0 
git-blame 1.8.0 
git-plus 8.7.1 
git-time-machine 2.1.0 
hex-view 1.0.1 
highlight-selected 0.17.0 
history-manager-editor 0.2.3 
Hydrogen 2.16.3 
hyperclick 0.1.5 
ide-bash 1.0.11 
ide-docker 0.1.0 
ide-flowtype 0.24.0 
ide-haskell 2.7.0 
ide-haskell-hie 0.12.0 
ide-java 0.9.1 
ide-json 0.2.1 
ide-mocha 2.6.0 
ide-php 0.7.18 
ide-powershell 0.1.0 
ide-python 1.9.7 
ide-rust 1.1.1 
ide-typescript 0.9.5 
intentions 2.1.1 
jquery-snippets 11.0.0 
language-apache 1.8.0 
language-awk 0.1.12 
language-cmake 1.2.0 
language-cython 0.3.0 
language-docker 1.1.8 
language-gdb 0.7.0 
language-ini 1.25.0 
language-javascript-jsx 0.3.7 
language-lua 0.9.11 
language-openscad 0.4.3 
language-powershell 5.0.0 
language-qml 1.2.0 
language-regexp 1.2.0 
language-roff 1.3.1 
language-rust 0.4.12 
language-systemd 0.1.1 
language-vba 0.2.5 
language-webassembly 1.2.0 
lint-scroll-marker 0.3.0 
linter 3.4.0 
linter-alex 7.0.0 
linter-autocomplete-jing 0.9.0 
linter-bootlint 1.1.9 
linter-chktex 1.4.0 
linter-clang 4.1.2 
linter-coverage 0.3.0 
linter-cppcheck 0.2.3 
linter-csslint 2.0.6 
linter-docker 0.3.2 
linter-dryer 0.4.1 
linter-emscripten 0.1.1 
linter-eslint 9.0.0 
linter-flake8 2.4.0 
linter-flint 2.0.0 
linter-flow 5.6.1 
linter-gcc 0.9.0 
linter-gjslint 1.6.0 
linter-glua 1.2.1 
linter-glualint 0.9.1 
linter-golinter 1.3.0 
linter-google-styleguide 1.0.0 
linter-govet 1.0.0 
linter-hadolint 1.0.0 
linter-hdevtools 1.10.0 
linter-hlint 2.1.0 
linter-htmlhint 1.6.3 
linter-htmllint 1.1.14 
linter-ibmstyleguide 2.0.0 
linter-javac 1.10.0 
linter-js-standard 7.0.0 
linter-js-yaml 1.4.6 
linter-jscs 4.2.4 
linter-jshint 3.1.19 
linter-jsonlint 1.4.0 
linter-just-say-no 0.7.6 
linter-kubectl 1.1.0 
linter-less 2.6.0 
linter-liferay 3.0.0 
linter-lsc 2.4.0 
linter-lua 2.0.0 
linter-lua-findglobals 1.2.0 
linter-luacheck 2.0.1 
linter-luaparse 0.2.0 
linter-markdown 5.2.11 
linter-markdownlint 2.0.2 
linter-marlint 1.0.1 
linter-matlab 1.3.0 
linter-mixed-indent 1.1.1 
linter-moose 0.6.0 
linter-mypy 2.6.11 
linter-node-markdownlint 1.2.1 
linter-package-json-validator 2.0.0 
linter-phan 2.0.0 
linter-php 1.6.1 
linter-phpcs 1.8.1 
linter-phpmd 2.0.2 
linter-proselint 3.3.0 
linter-pycodestyle 2.1.3 
linter-pydocstyle 0.4.7 
linter-pyflakes 0.3.2 
linter-pylama 0.10.1 
linter-python 3.1.2 
linter-revive 1.0.1 
linter-rust 1.0.1 
linter-rust-cargo 1.1.0 
linter-sass-lint 1.9.0 
linter-scss-lint 3.2.1 
linter-selective 0.3.1 
linter-shellcheck 1.6.0 
linter-spell 0.15.0 
linter-spell-javascript 0.9.0 
linter-stylelint 4.5.1 
linter-tidy 2.4.0 
linter-tslint 1.11.1 
linter-ui-default 3.4.1 
linter-write-good 0.9.3 
linter-xmllint 1.4.4 
linter-xo 0.31.0 
local-history 4.3.1 
minimap 4.40.0 
minimap-bookmarks 0.4.6 
minimap-cursorline 1.0.5 
minimap-find-and-replace 5.0.9 
minimap-git-diff 4.3.6 
minimap-highlight-selected 4.6.6 
minimap-linter 2.2.2 
minimap-pigments 0.2.2 
minimap-selection 4.5.5 
minimap-split-diff 0.3.7 
open-file 2.1.0 
open-terminal-here 2.3.2 
pdf-view 0.73.0 
pigments 0.40.6 
pp-markdown 0.0.2 
project-view 0.6.5 
python-debugger 0.2.0 
python-line-profiler 0.3.2 
python-linters 0.0.5 
quick-query 1.1.3 
quick-query-sqlite 0.4.1 
script 3.32.2 
scroll-marker 0.3.5 
sort-lines 0.19.0 
split-diff 1.6.1 
sync-settings 5.2.15 
teletype 0.13.4 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.5.3 
undo-tree 1.0.0 
```

**Comment by 0000matteo0000** [comment]
duplicate of #483
