### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by Achyut112** [atom-community/ide-python#504]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.7

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module './debugger/main'
Require stack:
- C:\Users\dell\.atom\packages\ide-python\dist\main.js
- C:\Users\dell\AppData\Local\atom\app-1.60.0\resources\app.asar\static\index.html

Error: Cannot find module './debugger/main'
Require stack:
- C:\Users\dell\.atom\packages\ide-python\dist\main.js
- C:\Users\dell\AppData\Local\atom\app-1.60.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:157942)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149229)
    at /packages/ide-python/dist/main.js:3:13)
    at /packages/ide-python/dist/main.js:174:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:14:1175135)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:3543231)
    at Package.activateNow (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:3531230)
    at ~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:1187666)
    at Emitter.emit (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:1189107)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:386501)
    at ~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:385252
    at TextEditorRegistry.updateAndMonitorEditorSettings (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:516355)
```

### Commands

```
```

### Non-Core Packages

```
ide-python 1.9.7 
```

**Comment by t3dium** [comment]
i get the same issue, just updated atom and my system. Any fixes?
