### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by cayubweeums** [atom-community/ide-python#511]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.61.0-beta0 x64
**Electron**: 11.5.0
**OS**: "Arch Linux"
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.7

### Stack Trace

Failed to activate the ide-python package

```
At call.getFileName is not a function

TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:278:25)
    at innerOk (assert.js:372:17)
    at ok (assert.js:392:3)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:45:21)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:305:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:16:17)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:14:62)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
autocomplete 0.47.0 
ide-java 0.9.1 
ide-python 1.9.7 
linter-flake8 2.4.0 
minimap 4.40.1 
python-autopep8 0.1.3 
script 3.32.2 
```

**Comment by jobalas** [comment]
i have the same error when i try to install

**Comment by t3dium** [comment]
i get the same issue, just updated atom and my system

**Comment by redst4r** [comment]
same here
