### ISSUE TITLE
failed to activate ide-python package

### ISSUE THREAD

**Issue by t3dium** [atom-community/ide-python#516]
error:
`call.getFileName is not a function`

Stack trace:
```
TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:278:25)
    at innerOk (assert.js:372:17)
    at ok (assert.js:392:3)
    at Object.<anonymous> (/home/computer/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:45:21)
    at Object.<anonymous> (/home/computer/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:305:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/computer/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:16:17)
    at Object.<anonymous> (/home/computer/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:278:25)
    at innerOk (assert.js:372:17)
    at ok (assert.js:392:3)
    at Object.<anonymous> (/home/computer/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:45:21)
    at Object.<anonymous> (/home/computer/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:305:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/computer/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:16:17)
    at Object.<anonymous> (/home/computer/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/computer/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:14:62)
    at Object.<anonymous> (/home/computer/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/computer/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:14:62)
    at Object.<anonymous> (/home/computer/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
```

**Comment by ntlspck** [comment]
same issue, is there a workaround?

**Comment by t3dium** [comment]
> same issue, is there a workaround?

I haven't found anything, does anyone know if this package is still maintained? The commits seem to just be from a bot, i might have to convert to another python package unfortunately
